### ISSUE TITLE
NATS.net JetStream singleton issues

### ISSUE THREAD

**Issue by Bykiev** [nats-io/nats.net#620]
### Observed behavior

When creating a singleton connection to NATS JetStream the error is thrown:

```
NATS.Client.JetStream.NatsJSApiNoResponseException: No API response received from the server
at NATS.Client.JetStream.NatsJSContext.JSRequestAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken)
at NATS.Client.JetStream.NatsJSContext.JSRequestAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken)
at NATS.Client.JetStream.NatsJSContext.JSRequestResponseAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken)
at NATS.Client.JetStream.NatsJSContext.GetStreamAsync(String stream, StreamInfoRequest request, CancellationToken cancellationToken)
at NATS.Client.KeyValueStore.NatsKVContext.GetStoreAsync(String bucket, CancellationToken cancellationToken)
```
My config:

```
builder.Services.AddNats(1, opts =>
{
    return new NATS.Client.Core.NatsOpts()
    {
        Name = name,
        Url = url,
        SerializerRegistry = NatsJsonSerializerRegistry.Default
    };
});
```

We've tried to use a connection pool with 1000 connection and everything is working as expected. Maybe it's not possible to subscribe and update the same store using one connection? I didn't find any information about it in the docs. And if it's not possible, how many connections should be in a connection pool?

### Expected behavior

No exception is thrown when NATS is registered as singleton

### Server and client version

NATS server 2.10.18
NATS .NET v2.3.3

### Host environment

Docker image

**Comment by mtmk** [comment]
we see this error sometimes. I'm assuming it happens intermittently and you have other consumers on the same connection. it may be head of line blocking. my guess is you can use keyed services and use a seperate connection for your consumers which may flood the connection.

**Comment by Bykiev** [comment]
Yes, we have a multiple consumers. We did some tests and I can see this error even with 10 connections in a pool. We've updated the NATS server docker image to v2.10.19, seems the problem still exists. What can we do to use NATS JS with multiple consumers?

**Comment by Bykiev** [comment]
After some time we didn't get any data via JS on some of the consumers, it seems the connection is dropped by someone or smth else is happened.

**Comment by Bykiev** [comment]
I did some research and this seems to be DI or pooler issue. I've removed the DI part from the project and created a single connection for watcher and another one for writing. This is working without any issues.

**Comment by Bykiev** [comment]
> are you on slack.nats.io maybe we can have a chat there
Unfortunately, It's not available in my country. I've created another issue https://github.com/nats-io/nats.net/issues/621, can be related to this issue

**Comment by mtmk** [comment]
@Bykiev afaiu this isn't an issue for you anymore. otherwise please feel free to reopen/comment on this issue or open a new one. thank you for your report btw really appreciated.
