### ISSUE TITLE
Request support for password protected PKCS#12 CertBundleFiles 

### ISSUE THREAD

**Issue by jmthanrahan** [nats-io/nats.net#693]
### Proposed change

Currently only CertBundleFiles that are not password protected are supported for SSL communication. Our certificates are password protected so we get the following error when attempting to use a password protected certificate.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Utils.LoadCertFromFile(String fileName, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName)

### Use case

PKCS#12 Certificates in use for our released product are password protected to meet internal and external security requirements.

**Comment by mtmk** [comment]
thanks for the report @jmthanrahan we have an implementation proposal here #694 at review.
